# Generated by Django 4.0.4 on 2022-05-16 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='access_token',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(default='', max_length=2200),
        ),
        migrations.AddField(
            model_name='post',
            name='caption',
            field=models.CharField(default='', max_length=2200),
        ),
        migrations.AddField(
            model_name='post',
            name='ig_user_id',
            field=models.CharField(default='', max_length=2200),
        ),
        migrations.AddField(
            model_name='post',
            name='is_carousel_item',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='location_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='post',
            name='media_type',
            field=models.CharField(choices=[('VD', 'VIDEO'), ('CR', 'CAROUSEL'), ('IM', 'IMAGE')], default='IM', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('RD', 'Ready'), ('UP', 'Uploaded'), ('PO', 'Posted'), ('ER', 'Error')], default='RD', max_length=2),
        ),
        migrations.AddField(
            model_name='post',
            name='thumb_offset',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(default='', max_length=2200),
        ),
    ]
